---
- import_tasks: clone_image.yml

- name: Include platform variables
  include_vars:
   dir: "{{ platform }}/{{ build_version }}"

- name: Launch VM with QEMU
  shell: "{{ qemu_command }} &"
  args:
    chdir: "{{ output_directory }}"
 
- name: Bootstrap VM
  expect:
    command: telnet localhost 8888
    responses: "{{ expect_responses }}"
    timeout: 300

- name: Wait for VM SSH
  wait_for:
    port: 8022
    search_regex: SSH

- name: Include platform config tasks
  include: "{{ platform }}/configure.yml"

- name: Kill QEMU
  shell: killall qemu-system-x86_64

- name: Rename built image to image_name
  shell: "mv {{ output_directory }}/cloned_image {{ output_directory }}/{{ image_name }}.qcow2"

- name: Create QEMU script
  template:
    src: "{{ platform }}/{{ build_version }}/qemu.j2"
    dest: "{{ output_directory }}/run_{{ image_name }}.sh"
    mode: 0775

- name: Create inventories folder
  file:
    path: "{{ output_directory }}/inventories"
    state: directory

- name: Create Ansible inventory
  template:
    src: "{{ platform }}/{{ build_version }}/inventory.j2"
    dest: "{{ output_directory }}/inventories/{{ image_name }}"

- import_tasks: build_wrapper_image.yml
  when: wrapper_linux_image is defined and wrapper_linux_image
