---
- name: Gather facts
  setup:

- name: Install pre-required packages
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - qemu-system-x86.x86_64
    - qemu-img.x86_64
    - libguestfs-tools
    - libselinux-python
    - telnet
    - pexpect
