---
- name: Check prereqs
  import_tasks: install_prereqs.yaml
  when: install_prereqs | bool

- name: Build image
  import_tasks: build_image.yaml

- name: build wrapper image
  import_tasks: build_wrapper_image.yaml
  when: wrap_images | bool
