---
- name: Check build_params variable is defined
  fail:
    msg: "Variable build_params needs to be defined"
  when: build_params is undefined

- name: Process build
  include_tasks: build_image.yml
  with_items: "{{ build_params }}"

- import_tasks: build_wrapper_image.yml
  when: wrapper_linux_image is defined
