---
- name: Convert image from vmdk to qcow2 format
  shell: qemu-img convert -f vmdk -O qcow2 cloned_image image.qcow2
  args:
    chdir: "{{ output_directory }}"

- name: Delete vmdk image file
  file:
    path: "{{ output_directory }}/cloned_image"
    state: absent

- name: Rename image.qcow2 to cloned_image
  shell: mv image.qcow2 cloned_image
  args:
    chdir: "{{ output_directory }}"

- name: Templatize EOS startup-config file
  template:
    src: eos/startup-config.j2
    dest: "{{ output_directory }}/startup-config"

- name: Copy EOS Ma1 dhclient script
  copy:
    src: eos/dhcp-ma1-on-boot.sh
    dest: "{{ output_directory }}/"

- name: Run guestfish commands on image
  shell: "guestfish add cloned_image : run : mount /dev/sda2 / : copy-in startup-config / : copy-in dhcp-ma1-on-boot.sh /"
  args:   
    chdir: "{{ output_directory }}"

- name: Clean up startup-config from output directory
  file:
    path: "{{ output_directory }}/startup-config"
    state: absent

- name: Clean up dhcp-ma1-on-boot.sh from output directory
  file:
    path: "{{ output_directory }}/dhcp-ma1-on-boot.sh"
    state: absent
